version: 2
updates:
    - package-ecosystem: "nuget"
      directory: "/AnkiStoryGenerator"
      schedule:
          interval: "monthly"
      groups:
          nuget-dependencies:
              patterns:
                  - "*"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      groups:
          github-actions-dependencies:
              patterns:
                  - "*"
                  
    - package-ecosystem: "npm"
        directory: "/WordExplainerScript"
        schedule:
        interval: "monthly"
        groups:
            github-actions-dependencies:
                patterns:
                - "*"